### ISSUE TITLE
cant start the SpellWork .exe

### ISSUE THREAD

**Issue by Farrarie** [TrinityCore/SpellWork#18]
I tried to start the .exe by clicking and by start as admin still nothing happen !

**Comment by Vincent-Michael** [comment]
try setting correct path for db2 / gt path

**Comment by Farrarie** [comment]
@Vincent-Michael thx for the reply but I edited both SpellWork.exe.config and app.config to these paths
<setting name=C:\DDD\ddd\repack\gt\ serializeAs="String"><value>gt</value>

<setting name=C:\DDD\aaa\repack\dbc\enUS\ serializeAs="String"><value>dbc</value>

but still the program don't open did I do anything wrong ?

**Comment by Aokromes** [comment]
this is not a forum. problems with configuration belongs to forum.
