### ISSUE TITLE
Stopped Working win 8.1/10 64bit

### ISSUE THREAD

**Issue by Hadifaren** [TrinityCore/SpellWork#19]
hi

I downloaded https://github.com/TrinityCore/SpellWork  and compiled release/debug , anycore/x64 in 

win8.1 and I got nothing(not work)

so I changed to win10 and still its not work :(

I have framework 4.6.2

please give some hand to solove

**Comment by DDuarte** [comment]
This is likely due to DBC files.

Just pushed dee5232a3e206b26348bfca198a7936671123b1c which adds an error message when it cannot find the files.

You need to place the DBC/DB2 files in the directory configured in the `app.config` file (by default it's `directory_of_the_spellwork_exe/dbc/enUS`)

**Comment by Hadifaren** [comment]
thank you , you are the first person who is really friendly

**Comment by Hadifaren** [comment]
thank you DDuarte You Are Best
