### ISSUE TITLE
Error when try compile or run spellwork 7.2

### ISSUE THREAD

**Issue by Xxxhackerxxx** [TrinityCore/SpellWork#20]
hi 
when i try to compile spellwork version 7.2
i got this error 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1003	Syntax error, ',' expected	SpellWork	E:\Spellwork7.2\SpellWork\SpellWork\Spell\SpellInfo.cs	199	Active
Error	CS0118	'SpellDescriptionVariablesEntry' is a type but is used like a variable	SpellWork	E:\Spellwork7.2\SpellWork\SpellWork\Spell\SpellInfo.cs	199	Active
Error	CS0103	The name 'variables' does not exist in the current context	SpellWork	E:\Spellwork7.2\SpellWork\SpellWork\Spell\SpellInfo.cs	199	Active
Error	CS0103	The name 'variables' does not exist in the current context	SpellWork	E:\Spellwork7.2\SpellWork\SpellWork\Spell\SpellInfo.cs	200	Active
```
and when i downloaded release 
7.2.0 (23826) (branch 7.x) Build status
and try to run spellwork was crashed 
thank for your attention .

**Comment by Xxxhackerxxx** [comment]
hi again ,
i change this line to it
`        public SpellInfo(SpellEntry spellEntry)
        {
            SpellDescriptionVariablesEntry variables;
            Spell = spellEntry;
            if (DBC.DBC.SpellDescriptionVariables.TryGetValue(spellEntry.DescriptionVariablesID, out variables))
                DescriptionVariables = variables;
        }
`
fixed .
thank you .

**Comment by DDuarte** [comment]
Which compiler do you use?

**Comment by Mihapro** [comment]
Microsoft Visual Studio Community 2015, Update 3
That change works. Tested for SpellWork 7.2.5.

**Comment by r00ty-tc** [comment]
Yeah, it's a new C# feature where you can define/initialize in the out keyword. So VS2017 would probably be fine with it.
