### ISSUE TITLE
Error when compiling SpellWork 7.2.5 (24330) using VS2015

### ISSUE THREAD

**Issue by Mihapro** [TrinityCore/SpellWork#21]
Line [SpellInfo.cs:199](https://github.com/TrinityCore/SpellWork/blob/7.x/SpellWork/Spell/SpellInfo.cs#L199) ...
```
if (DBC.DBC.SpellDescriptionVariables.TryGetValue(spellEntry.DescriptionVariablesID, out SpellDescriptionVariablesEntry variables))
```
... produces 4 errors (missing comma, 'SpellDescriptionVariablesEntry' type used as a variable, 'variables' does not exist, etc.). Using Microsoft Visual Studio Community 2015, Update 3.

I'm not familiar with C#, but it's better like this probably:
```
Spell = spellEntry;
SpellDescriptionVariablesEntry variables;
if (DBC.DBC.SpellDescriptionVariables.TryGetValue(spellEntry.DescriptionVariablesID, out variables))
    DescriptionVariables = variables;
```

**Comment by Aokromes** [comment]
#20
