### ISSUE TITLE
SpellWork.exe not starting

### ISSUE THREAD

**Issue by Smerdokryl** [TrinityCore/SpellWork#24]
I have pulled the latest 7.x version (5cb003754efe0fb2258bad23191949af43a0a25e) to use with TrinityCore rev. 172ccdb49929+. It has been compiled successfully, and I placed it in my server directory, making sure the dbc and gt paths are correct (the locale too).

When I run the .exe, nothing happens. There is no error message, and it is not in the process list.

**Comment by Shauren** [comment]
Because it works with 7.2.5 data, not 7.3.5

**Comment by Smerdokryl** [comment]
@Shauren It said 7.x, so I thought it would work. Is there a version that does work with 7.3.5?

**Comment by Shauren** [comment]
no
