### ISSUE TITLE
Nightly build broken for 2.4.3

### ISSUE THREAD

**Issue by Lillecarl** [TrinityCore/SpellWork#32]
Gets sent to an XML site on google storage

**Comment by jackpoz** [comment]
Since https://www.appveyor.com/blog/2018/06/05/artifacts-retention-policy-update/ artifacts are stored only for 6 months. Re-building last commit is enough to create again the artifacts (which is what I did. Please confirm the link works fine now).

**Comment by Lillecarl** [comment]
Works great now, thank you.
