### ISSUE TITLE
Nightly Builds unavailable

### ISSUE THREAD

**Issue by Sorikoff** [TrinityCore/SpellWork#33]
Nightly builds (like [3.3.5](https://appveyorcidata.blob.core.windows.net/dduarte-13923/spellwork-cs/1-0-93/whu0sba8yba6tsy1/SpellWork/SpellWork.zip?sv=2015-12-11&sr=c&sig=Inw9tzyYy4597bKzXVgpjTcguLxDE61YXF7qOdSG5iI%3D&st=2020-01-28T14%3A24%3A34Z&se=2020-01-28T14%3A30%3A34Z&sp=r)) are returning error `BlobNotFound`.
7.2.5 is working though.

**Comment by jackpoz** [comment]
AppVeyor artifacts expire after some months so the build has to be manually triggered again if no commits have been pushed for a while.
On it.

**Comment by jackpoz** [comment]
https://www.appveyor.com/docs/packaging-artifacts/#artifacts-retention-policy

**Comment by jackpoz** [comment]
>Artifacts older than 6 months are permanently removed from AppVeyor artifact storage.

**Comment by jackpoz** [comment]
All the branches have finished rebuilding on AppVeyor and the artifacts can be downloaded for the next 6 months. See you in 6 months for another manual build trigger!

**Comment by Aokromes** [comment]
we must compile all builds and store then on wiki xd
