### ISSUE TITLE
3.3.5 (master) branch Advanced Filter broken

### ISSUE THREAD

**Issue by Kitzunu** [TrinityCore/SpellWork#34]
In the https://github.com/TrinityCore/SpellWork/commit/4b39216abd68720428cbf370a1e64ea756a82473 version of SpellWork for 335 it seems to have trouble searching with the Advanced Filter.

I have tried using both my own compiled version (debug) as well as the appveyor version (release) and it doesn't seem to work.

I originally encountered this issue when I was searching for AttributeEx x & y != 0 but then I tested around with other search options as well and they seem not to work either.

in IRC @Shauren said that it is working for him and as I am assuming he is using the SpellWork for latest TC Master Branch I would then draw the conclusion that this is an issue with the 335 version

**Comment by Shauren** [comment]
No, I tested this on 335 version

![obraz](https://user-images.githubusercontent.com/297439/104965027-0e274b00-59de-11eb-8f98-5f7aa8197815.png)

**Comment by Kitzunu** [comment]
Thats weird, I got this. Could it be due to bad DBC's?
![image](https://user-images.githubusercontent.com/24550914/104965541-32375c00-59df-11eb-902f-fe1ef25379f7.png)

**Comment by Shauren** [comment]
I have a silly question, did you by any chance press that "Search" button?

**Comment by Kitzunu** [comment]
Yea I did, I went quite insane and pressed it a couple of times xD

**Comment by Shauren** [comment]
That is why it doesn't work. That button only does a search using the top 3 inputs. To get it to filter by the family/aura/effect/target/advanced, you need to change one of the dropdowns or press enter when focusing one of advanced inputs

**Comment by Kitzunu** [comment]
Interesting, yep. Pressing enter works.

Thanks for the assistance man!
